#network
base: 64
max_filters: 256
num_downsamples: 2
num_resblocks: 9
use_bias: True
act: 'relu'
norm: 'instance'

#PatchNCE
units: 256
num_patches: 256
tau: 0.07
nce_layers: [0, 3, 5, 7, 11]

#gan
gan_mode: 'lsgan'
disc_type: 'patch'

#loss
lambda_nce: 1.0
