#network
base: 64
num_downsamples: 2
num_resblocks: 9
use_bias: True
act: 'relu'
norm: 'instance'

#loss
loss_type: 'infonce'
disc_type: 'patch'
multi_scale: True
gan_mode: 'lsgan'
units: 256
num_patches: 1024
tau: 0.07
per_layers: [0, 2, 5, 10, 15, 20]
use_identity: True
