#network
base: 64
n_embs: 256
num_downsamples: 2
num_resblocks: 4
use_bias: True
act: 'relu'
norm: 'instance'

#gan
gan_mode: 'lsgan'
disc_type: 'patch'

#loss
lambda_idt: 1.0
lambda_cyc: 1.0
beta: 0.25
